### ISSUE TITLE
Tippfehler S. 12

### ISSUE THREAD

**Issue by minaaz15** [Boeserwolff/Info-I#1]
Hallo Julian, 
da ist ein kleiner Tippfehler, ich denke, es heißt auf Seite 12, Bsp. Summer nat. Zahlen
NICHT:    (≥(+ x 1 x 2 ) (max x 2 x 2 ))))
SONDERN:    (≥(+ x 1 x 2 ) (max x 1 x 2 ))))

Vgl. Screenshot:
![x1](https://cloud.githubusercontent.com/assets/15271402/20410409/2473d4a4-ad1d-11e6-932b-3e1175f53565.jpg)
Viele Grüße, Nina 

PS: Super Skript!

**Comment by Boeserwolff** [comment]
Danke für den Hinweis, ist gefixt
Grüße
